Repository SubjectiveLabs/SubjectiveAssembly, pull requests merged in 2023-09, with the labels that each got.

#15 Icon
  frontend/index.html
  frontend/public/favicon.png
Labels: enhancement

#16 enable dependabot
  .github/dependabot.yml
Labels: enhancement

#23 Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#33 update readme
  README.md
Labels: enhancement

#34 style and add password edit
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/Link/index.tsx
Labels: enhancement

#35 implement thanks system
  backend/src/main.rs
  backend/src/thanks.rs
  frontend/src/App.tsx
  frontend/src/backend.tsx
  frontend/src/components/Alert/index.tsx
  frontend/src/components/Header/index.tsx
Labels: enhancement

#38 text sizing changes
  frontend/src/components/Header/index.tsx
Labels: enhancement

#46 invisible element text size
  frontend/src/components/Header/index.tsx
Labels: Bug

#47 Tweak sizing and spacing and remove redundant alert.
  frontend/src/App.tsx
  frontend/src/components/Bell/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Icons/index.tsx
  frontend/src/components/Link/index.tsx
  frontend/src/components/Login/index.tsx
  frontend/src/components/Message/index.tsx
Labels: enhancement

#49 clean up context obj and impl autorefresh on settings screen
  frontend/src/App.tsx
  frontend/src/components/Bell/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Link/index.tsx
  frontend/src/components/Login/index.tsx
  frontend/src/components/Settings/index.tsx
Labels: enhancement

#58 Fix pencil background to match app background.
  frontend/src/components/Header/index.tsx
Labels: enhancement, good first issue

#65 impl dupe
  frontend/src/App.tsx
  frontend/src/components/Bell/index.tsx
  frontend/src/components/Icons/index.tsx
Labels: enhancement

#75 fix pencil
  frontend/src/components/Header/index.tsx
Labels: bug
